my-kujira:
  build: "."
  volumes:
    - ../Downloads/kujira:/root/volume
  tty: true
  cap_add:
    - SYS_PTRACE
  security_opt:
    - seccomp:unconfined
  environment:                                                            
    - EDITOR=vim  
