my-kujira:
  ports:
    - "1-65535:1-65535"
  build: "."
  volumes:
    - /mnt/c/Users/akako/Downloads/Kujira:/root/volume
  tty: true
  cap_add:
    - SYS_PTRACE
  security_opt:
    - seccomp:unconfined
  environment:                                                            
    - EDITOR=vim  
