#!/usr/bin/env python

import sys, os
import subprocess


# set variable
VOLUME = 'volume'
FOLDER = '.oh-my-kujira'
KUJIRA_PATH = os.path.expanduser('~') + '/' + FOLDER
START_UP = 'docker-compose run my-kujira zsh'

if len(sys.argv) > 1:
    # copy or move file
    if sys.argv[1]  == '-m' and len(sys.argv) > 2:
        file_index = 2
        cmd = 'sudo mv {0} {1}/{2}'
    else:
        file_index = 1
        cmd = 'sudo cp -r {0} {1}/{2}'

    cmd = cmd.format(sys.argv[file_index], KUJIRA_PATH, VOLUME)
    os.system(cmd)

# run kujira
os.chdir(KUJIRA_PATH)
os.system(START_UP)

